2018-03-29 18:30:09,597 INFO: Microblog startup [in /Users/dlmy/Documents/works/python/microblog/app/__init__.py:45]
2018-03-30 09:11:25,692 INFO: Microblog startup [in /Users/dlmy/Documents/works/python/microblog/app/__init__.py:45]
2018-03-30 09:18:23,385 INFO: Microblog startup [in /Users/dlmy/Documents/works/python/microblog/app/__init__.py:45]
2018-03-30 09:28:37,749 INFO: Microblog startup [in /Users/dlmy/Documents/works/python/microblog/app/__init__.py:45]
2018-03-30 09:29:35,001 INFO: Microblog startup [in /Users/dlmy/Documents/works/python/microblog/app/__init__.py:45]
2018-03-30 09:29:43,774 INFO: Microblog startup [in /Users/dlmy/Documents/works/python/microblog/app/__init__.py:45]
2018-03-30 09:48:03,025 INFO: Microblog startup [in /Users/dlmy/Documents/works/python/microblog/app/__init__.py:45]
2018-03-30 09:50:05,013 INFO: Microblog startup [in /Users/dlmy/Documents/works/python/microblog/app/__init__.py:45]
2018-03-30 09:54:28,872 INFO: Microblog startup [in /Users/dlmy/Documents/works/python/microblog/app/__init__.py:45]
2018-03-30 09:54:42,817 INFO: Microblog startup [in /Users/dlmy/Documents/works/python/microblog/app/__init__.py:45]
2018-03-30 09:57:58,998 INFO: Microblog startup [in /Users/dlmy/Documents/works/python/microblog/app/__init__.py:45]
2018-03-30 10:04:12,283 INFO: Microblog startup [in /Users/dlmy/Documents/works/python/microblog/app/__init__.py:45]
2018-03-30 16:45:51,644 INFO: Microblog startup [in /Users/dlmy/Documents/works/python/microblog/app/__init__.py:45]
2018-03-30 17:13:17,106 INFO: Microblog startup [in /Users/dlmy/Documents/works/python/microblog/app/__init__.py:45]
2018-03-30 17:13:25,227 ERROR: Exception on /explore [GET] [in /Users/dlmy/Documents/works/python/microblog/venv/lib/python3.6/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/Users/dlmy/Documents/works/python/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/dlmy/Documents/works/python/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/dlmy/Documents/works/python/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/dlmy/Documents/works/python/microblog/venv/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/dlmy/Documents/works/python/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/dlmy/Documents/works/python/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/dlmy/Documents/works/python/microblog/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/dlmy/Documents/works/python/microblog/app/routes.py", line 138, in explore
    return render_template('index.html', title='Explore', posts=posts)
  File "/Users/dlmy/Documents/works/python/microblog/venv/lib/python3.6/site-packages/flask/templating.py", line 133, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/dlmy/Documents/works/python/microblog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/dlmy/Documents/works/python/microblog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/dlmy/Documents/works/python/microblog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Users/dlmy/Documents/works/python/microblog/venv/lib/python3.6/site-packages/jinja2/loaders.py", line 125, in load
    code = environment.compile(source, name, filename)
  File "/Users/dlmy/Documents/works/python/microblog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 591, in compile
    self.handle_exception(exc_info, source_hint=source_hint)
  File "/Users/dlmy/Documents/works/python/microblog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/dlmy/Documents/works/python/microblog/venv/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/dlmy/Documents/works/python/microblog/app/templates/index.html", line 20, in template
    {% endblock %}
  File "/Users/dlmy/Documents/works/python/microblog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 497, in _parse
    return Parser(self, source, name, encode_filename(filename)).parse()
  File "/Users/dlmy/Documents/works/python/microblog/venv/lib/python3.6/site-packages/jinja2/parser.py", line 901, in parse
    result = nodes.Template(self.subparse(), lineno=1)
  File "/Users/dlmy/Documents/works/python/microblog/venv/lib/python3.6/site-packages/jinja2/parser.py", line 883, in subparse
    rv = self.parse_statement()
  File "/Users/dlmy/Documents/works/python/microblog/venv/lib/python3.6/site-packages/jinja2/parser.py", line 130, in parse_statement
    return getattr(self, 'parse_' + self.stream.current.value)()
  File "/Users/dlmy/Documents/works/python/microblog/venv/lib/python3.6/site-packages/jinja2/parser.py", line 268, in parse_block
    node.body = self.parse_statements(('name:endblock',), drop_needle=True)
  File "/Users/dlmy/Documents/works/python/microblog/venv/lib/python3.6/site-packages/jinja2/parser.py", line 165, in parse_statements
    result = self.subparse(end_tokens)
  File "/Users/dlmy/Documents/works/python/microblog/venv/lib/python3.6/site-packages/jinja2/parser.py", line 883, in subparse
    rv = self.parse_statement()
  File "/Users/dlmy/Documents/works/python/microblog/venv/lib/python3.6/site-packages/jinja2/parser.py", line 130, in parse_statement
    return getattr(self, 'parse_' + self.stream.current.value)()
  File "/Users/dlmy/Documents/works/python/microblog/venv/lib/python3.6/site-packages/jinja2/parser.py", line 213, in parse_if
    'name:endif'))
  File "/Users/dlmy/Documents/works/python/microblog/venv/lib/python3.6/site-packages/jinja2/parser.py", line 165, in parse_statements
    result = self.subparse(end_tokens)
  File "/Users/dlmy/Documents/works/python/microblog/venv/lib/python3.6/site-packages/jinja2/parser.py", line 883, in subparse
    rv = self.parse_statement()
  File "/Users/dlmy/Documents/works/python/microblog/venv/lib/python3.6/site-packages/jinja2/parser.py", line 144, in parse_statement
    self.fail_unknown_tag(token.value, token.lineno)
  File "/Users/dlmy/Documents/works/python/microblog/venv/lib/python3.6/site-packages/jinja2/parser.py", line 97, in fail_unknown_tag
    return self._fail_ut_eof(name, self._end_token_stack, lineno)
  File "/Users/dlmy/Documents/works/python/microblog/venv/lib/python3.6/site-packages/jinja2/parser.py", line 90, in _fail_ut_eof
    self.fail(' '.join(message), lineno)
  File "/Users/dlmy/Documents/works/python/microblog/venv/lib/python3.6/site-packages/jinja2/parser.py", line 59, in fail
    raise exc(msg, lineno, self.name, self.filename)
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'endblock'. You probably made a nesting mistake. Jinja is expecting this tag, but currently looking for 'elif' or 'else' or 'endif'. The innermost block that needs to be closed is 'if'.
2018-03-30 17:32:18,724 INFO: Microblog startup [in /Users/dlmy/Documents/works/python/microblog/app/__init__.py:45]
2018-03-30 17:35:54,929 INFO: Microblog startup [in /Users/dlmy/Documents/works/python/microblog/app/__init__.py:45]
2018-03-30 17:52:03,355 INFO: Microblog startup [in /Users/dlmy/Documents/works/python/microblog/app/__init__.py:45]
2018-03-30 17:54:47,721 INFO: Microblog startup [in /Users/dlmy/Documents/works/python/microblog/app/__init__.py:45]
2018-03-30 17:57:58,643 INFO: Microblog startup [in /Users/dlmy/Documents/works/python/microblog/app/__init__.py:45]
2018-03-30 17:58:24,581 INFO: Microblog startup [in /Users/dlmy/Documents/works/python/microblog/app/__init__.py:45]
2018-03-30 17:58:48,694 INFO: Microblog startup [in /Users/dlmy/Documents/works/python/microblog/app/__init__.py:45]
2018-03-30 18:00:13,236 INFO: Microblog startup [in /Users/dlmy/Documents/works/python/microblog/app/__init__.py:45]
2018-03-30 21:30:40,170 INFO: Microblog startup [in /Users/dlmy/Documents/works/python/microblog/app/__init__.py:45]
2018-03-30 21:32:36,422 INFO: Microblog startup [in /Users/dlmy/Documents/works/python/microblog/app/__init__.py:45]
2018-03-30 21:42:05,057 INFO: Microblog startup [in /Users/dlmy/Documents/works/python/microblog/app/__init__.py:45]
2018-03-30 21:56:03,897 INFO: Microblog startup [in /Users/dlmy/Documents/works/python/microblog/app/__init__.py:47]
2018-04-04 09:18:11,576 INFO: Microblog startup [in /Users/dlmy/Documents/works/python/microblog/app/__init__.py:47]
2018-04-04 10:49:29,138 INFO: Microblog startup [in /Users/dlmy/Documents/works/python/microblog/app/__init__.py:47]
